// Database types for Supabase
// This file will be auto-generated by Supabase CLI after migration
// For now, we define the expected schema manually

export interface Database {
  public: {
    Tables: {
      sessions: {
        Row: {
          id: string;
          user_id: string;
          session_type: 'work' | 'short_break' | 'long_break';
          duration_seconds: number;
          completed_at: string;
          tag: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          session_type: 'work' | 'short_break' | 'long_break';
          duration_seconds: number;
          completed_at: string;
          tag?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          session_type?: 'work' | 'short_break' | 'long_break';
          duration_seconds?: number;
          completed_at?: string;
          tag?: string | null;
          created_at?: string;
        };
      };
      user_settings: {
        Row: {
          id: string;
          user_id: string;
          work_duration: number;
          short_break_duration: number;
          long_break_duration: number;
          sessions_until_long_break: number;
          theme: string;
          accent_color: string;
          icon_style: string;
          notifications_enabled: boolean;
          sound_enabled: boolean;
          sound_volume: number;
          auto_start: boolean;
          tags: string[];
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          work_duration?: number;
          short_break_duration?: number;
          long_break_duration?: number;
          sessions_until_long_break?: number;
          theme?: string;
          accent_color?: string;
          icon_style?: string;
          notifications_enabled?: boolean;
          sound_enabled?: boolean;
          sound_volume?: number;
          auto_start?: boolean;
          tags?: string[];
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          work_duration?: number;
          short_break_duration?: number;
          long_break_duration?: number;
          sessions_until_long_break?: number;
          theme?: string;
          accent_color?: string;
          icon_style?: string;
          notifications_enabled?: boolean;
          sound_enabled?: boolean;
          sound_volume?: number;
          auto_start?: boolean;
          tags?: string[];
          updated_at?: string;
        };
      };
      goals: {
        Row: {
          id: string;
          user_id: string;
          daily_sessions: number | null;
          daily_minutes: number | null;
          weekly_sessions: number | null;
          weekly_minutes: number | null;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          daily_sessions?: number | null;
          daily_minutes?: number | null;
          weekly_sessions?: number | null;
          weekly_minutes?: number | null;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          daily_sessions?: number | null;
          daily_minutes?: number | null;
          weekly_sessions?: number | null;
          weekly_minutes?: number | null;
          updated_at?: string;
        };
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
  };
}
